name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install inkscape / imagemagick
        run: |
          sudo add-apt-repository -y ppa:inkscape.dev/stable
          sudo apt-get -y update
          sudo apt-get install -y inkscape imagemagick

      - name: Generate ico
        run: |
          ./convert2ico.sh

      - name: pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "*.ico"

      - name: tagged-release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "*.ico"

